version: "3"
services:
  back-office:
    build:
      context: .
      dockerfile: ./apps/back-office/Dockerfile
    ports:
      - 3000:3000
    command: ["node", "./apps/back-office/server.js"]
  demo:
    build:
      context: .
      dockerfile: ./apps/demo/Dockerfile
    ports:
      - 3002:3002
    command: ["node", "./apps/demo/server.js"]
